"""Correction héritage polymorphique

Revision ID: 7ae9d8da05c4
Revises: 
Create Date: 2025-03-16 14:45:20.351605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7ae9d8da05c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clients_otps_expires_at', table_name='clients_otps')
    op.drop_index('ix_clients_otps_id', table_name='clients_otps')
    op.drop_index('session_id', table_name='clients_otps')
    op.drop_table('clients_otps')
    op.drop_index('email', table_name='centres_etat_civil')
    op.drop_index('ix_centres_etat_civil_id', table_name='centres_etat_civil')
    op.drop_index('nom', table_name='centres_etat_civil')
    op.drop_index('reference', table_name='centres_etat_civil')
    op.drop_index('telephone', table_name='centres_etat_civil')
    op.drop_table('centres_etat_civil')
    op.drop_index('ix_permissions_id', table_name='permissions')
    op.drop_table('permissions')
    op.drop_index('ix_clients_sessions_expires_at', table_name='clients_sessions')
    op.drop_index('ix_clients_sessions_id', table_name='clients_sessions')
    op.drop_table('clients_sessions')
    op.drop_index('ix_clients_email', table_name='clients')
    op.drop_index('ix_clients_id', table_name='clients')
    op.drop_index('ix_clients_phone', table_name='clients')
    op.drop_index('unique_email_phone', table_name='clients')
    op.drop_table('clients')
    op.drop_table('acte_naissance')
    op.drop_index('ix_roles_id', table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_organisations_id', table_name='organisations')
    op.drop_index('nom', table_name='organisations')
    op.drop_index('reference', table_name='organisations')
    op.drop_table('organisations')
    op.drop_index('ix_demandes_id', table_name='demandes')
    op.drop_index('numero_demande', table_name='demandes')
    op.drop_table('demandes')
    op.drop_index('ix_motifs_demandes_id', table_name='motifs_demandes')
    op.drop_table('motifs_demandes')
    op.drop_table('user_permissions')
    op.drop_index('email', table_name='utilisateurs')
    op.drop_index('ix_utilisateurs_id', table_name='utilisateurs')
    op.drop_table('utilisateurs')
    op.drop_table('role_permissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permissions',
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('permission_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name='role_permissions_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='role_permissions_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('utilisateurs',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nom', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('prenom', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('mot_de_passe', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('status', mysql.ENUM('ACTIF', 'INACTIF', 'REVOQUE'), nullable=False),
    sa.Column('date_creation', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('date_modification', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('organisation_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('centre_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('affecte_par_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('date_affectation', mysql.DATETIME(), nullable=True),
    sa.Column('organisation_affecte_par_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('date_affectation_organisation', mysql.DATETIME(), nullable=True),
    sa.Column('centre_affecte_par_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('date_affectation_centre', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['affecte_par_id'], ['utilisateurs.id'], name='utilisateurs_ibfk_4', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['centre_affecte_par_id'], ['utilisateurs.id'], name='utilisateurs_ibfk_6', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['centre_id'], ['centres_etat_civil.id'], name='utilisateurs_ibfk_3', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_affecte_par_id'], ['utilisateurs.id'], name='utilisateurs_ibfk_5', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name='utilisateurs_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='utilisateurs_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_utilisateurs_id', 'utilisateurs', ['id'], unique=False)
    op.create_index('email', 'utilisateurs', ['email'], unique=True)
    op.create_table('user_permissions',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('permission_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name='user_permissions_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateurs.id'], name='user_permissions_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('motifs_demandes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('motif', mysql.ENUM('DOCUMENT_INCOMPLET', 'DOCUMENT_NON_VALIDE', 'DOCUMENT_NON_LISIBLE', 'DOCUMENT_NON_AUTHENTIQUE', 'DOCUMENT_NON_CONFORME', 'DOCUMENT_MANQUANT', 'DOCUMENT_NON_TRADUIT', 'INFORMATIONS_INCORRECTES', 'DONNEES_INCOHERENTES', 'IDENTITE_NON_VERIFIEE', 'INFORMATION_OBSOLETE', 'ADRESSE_NON_VALIDE', 'DOSSIER_DUPLIQUE', 'DOSSIER_NON_AUTORISE', 'NON_RESPECT_DES_DELAIS', 'ABSENCE_DE_PIECES_JUSTIFICATIVES', 'DEMANDE_NON_RECEVABLE', 'QUOTA_DEPASSE', 'ERREUR_ENREGISTREMENT', 'INCOHERENCE_BASE_DE_DONNEES', 'SERVICE_TEMPORAIREMENT_INDISPONIBLE', 'FORMULAIRE_INVALIDE', 'PROBLEME_CONNEXION'), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_motifs_demandes_id', 'motifs_demandes', ['id'], unique=False)
    op.create_table('demandes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('client_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('numero_demande', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('type_document', mysql.ENUM('ACTE_NAISSANCE', 'ACTE_MARIAGE', 'ACTE_DECES', 'CERTIFICAT_NATIONALITE', 'CASIER_JUDICIAIRE', 'PLUMITIF'), nullable=False),
    sa.Column('raison_demande', mysql.ENUM('PERTE_DOCUMENT', 'VOL_DOCUMENT', 'DETERIORATION_DOCUMENT', 'RECTIFICATION_ERREUR', 'CHANGEMENT_ETAT_CIVIL', 'UTILISATION_ETRANGER', 'DEMANDE_DUPLICATA', 'EXIGENCE_ADMINISTRATIVE', 'REGULARISATION_SITUATION', 'DEMANDE_PERSONNELLE', 'DOSSIER_SCOLAIRE', 'EMPLOI_RECRUTEMENT', 'DEMANDE_VISA', 'SUCCESSION_HERITAGE', 'MARIAGE', 'CREATION_ENTREPRISE', 'DOSSIER_BANCAIRE'), nullable=False),
    sa.Column('status', mysql.ENUM('EN_COURS', 'VALIDE', 'REJETE', 'TRANSFERE'), nullable=False),
    sa.Column('motif_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('valide_par_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('date_validation', mysql.DATETIME(), nullable=True),
    sa.Column('rejete_par_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('date_rejet', mysql.DATETIME(), nullable=True),
    sa.Column('agent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('date_affectation_agent', mysql.DATETIME(), nullable=True),
    sa.Column('agent_site_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('date_affectation_agent_site', mysql.DATETIME(), nullable=True),
    sa.Column('date_creation', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('date_modification', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['utilisateurs.id'], name='demandes_ibfk_5', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['agent_site_id'], ['utilisateurs.id'], name='demandes_ibfk_6', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='demandes_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['motif_id'], ['motifs_demandes.id'], name='demandes_ibfk_2', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rejete_par_id'], ['utilisateurs.id'], name='demandes_ibfk_4', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['valide_par_id'], ['utilisateurs.id'], name='demandes_ibfk_3', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('numero_demande', 'demandes', ['numero_demande'], unique=True)
    op.create_index('ix_demandes_id', 'demandes', ['id'], unique=False)
    op.create_table('organisations',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nom', mysql.ENUM('BUNEC', 'MINJUSTICE'), nullable=False),
    sa.Column('reference', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('reference', 'organisations', ['reference'], unique=True)
    op.create_index('nom', 'organisations', ['nom'], unique=True)
    op.create_index('ix_organisations_id', 'organisations', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nom', mysql.ENUM('SUPER_ADMINISTRATEUR', 'ADMINISTRATEUR', 'AGENT', 'OPERATEUR_SUR_SITE'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_roles_id', 'roles', ['id'], unique=False)
    op.create_table('acte_naissance',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reference_centre_civil', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('numero_acte_naissance', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('date_creation_acte', mysql.DATETIME(), nullable=True),
    sa.Column('declare_par', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('autorise_par', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_pere', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('date_naissance_pere', mysql.DATETIME(), nullable=True),
    sa.Column('lieu_naissance_pere', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('profession_pere', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom_mere', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('date_naissance_mere', mysql.DATETIME(), nullable=True),
    sa.Column('lieu_naissance_mere', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('profession_mere', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('prenom', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nom', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('sexe', mysql.ENUM('MASCULIN', 'FEMININ'), nullable=False),
    sa.Column('date_naissance', mysql.DATETIME(), nullable=False),
    sa.Column('lieu_naissance', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['demandes.id'], name='acte_naissance_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('clients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.CheckConstraint('`email` is not null or `phone` is not null', name='check_email_or_phone'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('unique_email_phone', 'clients', ['email', 'phone'], unique=True)
    op.create_index('ix_clients_phone', 'clients', ['phone'], unique=True)
    op.create_index('ix_clients_id', 'clients', ['id'], unique=False)
    op.create_index('ix_clients_email', 'clients', ['email'], unique=True)
    op.create_table('clients_sessions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('client_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='clients_sessions_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_clients_sessions_id', 'clients_sessions', ['id'], unique=False)
    op.create_index('ix_clients_sessions_expires_at', 'clients_sessions', ['expires_at'], unique=False)
    op.create_table('permissions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nom', mysql.ENUM('CREER_UTILISATEUR', 'LIRE_UTILISATEUR', 'MODIFIER_UTILISATEUR', 'SUPPRIMER_UTILISATEUR', 'ACTIVER_DESACTIVER_UTILISATEUR', 'REINITIALISER_MOT_DE_PASSE', 'CREER_ROLE', 'LIRE_ROLE', 'MODIFIER_ROLE', 'SUPPRIMER_ROLE', 'ASSIGNER_PERMISSION', 'CREER_DEMANDE', 'LIRE_DEMANDE', 'MODIFIER_DEMANDE', 'SUPPRIMER_DEMANDE', 'VALIDER_DEMANDE', 'REJETER_DEMANDE', 'TRANSFERER_DEMANDE', 'AFFECTER_AGENT', 'REASSIGNER_AGENT', 'CREER_DOCUMENT', 'LIRE_DOCUMENT', 'MODIFIER_DOCUMENT', 'SUPPRIMER_DOCUMENT', 'AUTHENTIFIER_DOCUMENT', 'CERTIFIER_DOCUMENT', 'CREER_CLIENT', 'LIRE_CLIENT', 'MODIFIER_CLIENT', 'SUPPRIMER_CLIENT', 'CREER_MOTIF', 'LIRE_MOTIF', 'MODIFIER_MOTIF', 'SUPPRIMER_MOTIF', 'CONSULTER_STATISTIQUES', 'GENERER_RAPPORT', 'CONSULTER_HISTORIQUE_ACTIONS', 'CREER_ORGANISATION', 'LIRE_ORGANISATION', 'MODIFIER_ORGANISATION', 'SUPPRIMER_ORGANISATION', 'EXPORTER_DONNEES', 'IMPORTER_DONNEES', 'GESTION_PARAMETRES', 'GESTION_CLIENTS', 'VIEW_CLIENTS', 'VIEW_CLIENT_DETAILS', 'GESTION_SESSIONS', 'VIEW_SESSIONS', 'CREATE_SESSION', 'ACTIVATE_SESSION', 'EDIT_SESSION', 'DELETE_SESSION', 'VIEW_SESSION_DETAILS', 'GESTION_OTP', 'VIEW_OTPS', 'CREATE_OTP', 'VALIDATE_OTP', 'DELETE_OTP', 'VIEW_OTP_DETAILS', 'GESTION_CENTRE_ETAT_CIVIL', 'CREER_CENTRE_ETAT_CIVIL', 'VOIR_CENTRE_ETAT_CIVIL', 'MODIFIER_CENTRE_ETAT_CIVIL', 'SUPPRIMER_CENTRE_ETAT_CIVIL', 'CONSULTER_UTILISATEURS_CENTRE', 'GESTION_ORGANISATIONS', 'VOIR_ORGANISATION', 'CONSULTER_UTILISATEURS_ORGANISATION'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_permissions_id', 'permissions', ['id'], unique=False)
    op.create_table('centres_etat_civil',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('reference', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('nom', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('adresse', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('telephone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('telephone', 'centres_etat_civil', ['telephone'], unique=True)
    op.create_index('reference', 'centres_etat_civil', ['reference'], unique=True)
    op.create_index('nom', 'centres_etat_civil', ['nom'], unique=True)
    op.create_index('ix_centres_etat_civil_id', 'centres_etat_civil', ['id'], unique=False)
    op.create_index('email', 'centres_etat_civil', ['email'], unique=True)
    op.create_table('clients_otps',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('session_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('otp_code', mysql.VARCHAR(length=5), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['clients_sessions.id'], name='clients_otps_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('session_id', 'clients_otps', ['session_id'], unique=True)
    op.create_index('ix_clients_otps_id', 'clients_otps', ['id'], unique=False)
    op.create_index('ix_clients_otps_expires_at', 'clients_otps', ['expires_at'], unique=False)
    # ### end Alembic commands ###
