"""Nom de la migration

Revision ID: d5eabfd99fe8
Revises: 
Create Date: 2025-03-11 13:28:38.310129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd5eabfd99fe8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_demandes_id', table_name='demandes')
    op.drop_index('request_number', table_name='demandes')
    op.drop_table('demandes')
    op.drop_index('ix_clients_otps_expires_at', table_name='clients_otps')
    op.drop_index('ix_clients_otps_id', table_name='clients_otps')
    op.drop_index('session_id', table_name='clients_otps')
    op.drop_table('clients_otps')
    op.drop_index('ix_clients_sessions_expires_at', table_name='clients_sessions')
    op.drop_index('ix_clients_sessions_id', table_name='clients_sessions')
    op.drop_table('clients_sessions')
    op.drop_index('ix_clients_email', table_name='clients')
    op.drop_index('ix_clients_id', table_name='clients')
    op.drop_index('ix_clients_phone', table_name='clients')
    op.drop_index('unique_email_phone', table_name='clients')
    op.drop_table('clients')
    op.drop_index('demande_id', table_name='documents')
    op.drop_index('ix_documents_id', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('demande_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('file_path', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('file_type', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('file_size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('checksum', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes.id'], name='documents_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_documents_id', 'documents', ['id'], unique=False)
    op.create_index('demande_id', 'documents', ['demande_id'], unique=True)
    op.create_table('clients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.CheckConstraint('`email` is not null or `phone` is not null', name='check_email_or_phone'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('unique_email_phone', 'clients', ['email', 'phone'], unique=True)
    op.create_index('ix_clients_phone', 'clients', ['phone'], unique=True)
    op.create_index('ix_clients_id', 'clients', ['id'], unique=False)
    op.create_index('ix_clients_email', 'clients', ['email'], unique=True)
    op.create_table('clients_sessions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('client_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='clients_sessions_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_clients_sessions_id', 'clients_sessions', ['id'], unique=False)
    op.create_index('ix_clients_sessions_expires_at', 'clients_sessions', ['expires_at'], unique=False)
    op.create_table('clients_otps',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('session_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('otp_code', mysql.VARCHAR(length=5), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['clients_sessions.id'], name='clients_otps_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('session_id', 'clients_otps', ['session_id'], unique=True)
    op.create_index('ix_clients_otps_id', 'clients_otps', ['id'], unique=False)
    op.create_index('ix_clients_otps_expires_at', 'clients_otps', ['expires_at'], unique=False)
    op.create_table('demandes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('session_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('request_number', mysql.VARCHAR(length=22), nullable=False),
    sa.Column('document_type', mysql.ENUM('ACTE_DE_NAISSANCE', 'ACTE_DE_MARIAGE', 'ACTE_DE_DECES', 'CERTIFICAT_DE_NATIONALITE', 'EXTRAIT_DU_CASIER_JUDICIAIRE', 'EXTRAIT_DU_PLUMITIF'), nullable=False),
    sa.Column('request_reason', mysql.ENUM('RAISON1', 'RAISON2', 'RAISON3'), nullable=False),
    sa.Column('civil_center_reference', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('birth_act_number', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('birth_act_creation_date', mysql.DATETIME(), nullable=False),
    sa.Column('declaration_by', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('authorized_by', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('gender', mysql.ENUM('MASCULIN', 'FEMININ'), nullable=False),
    sa.Column('birth_date', mysql.DATETIME(), nullable=False),
    sa.Column('birth_place', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('father_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('father_birth_date', mysql.DATETIME(), nullable=True),
    sa.Column('father_birth_place', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('father_profession', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('mother_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('mother_birth_date', mysql.DATETIME(), nullable=True),
    sa.Column('mother_birth_place', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('mother_profession', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.ENUM('EN_COURS', 'VALIDE', 'REFUSE'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['clients_sessions.id'], name='demandes_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('request_number', 'demandes', ['request_number'], unique=True)
    op.create_index('ix_demandes_id', 'demandes', ['id'], unique=False)
    # ### end Alembic commands ###
