# app/models/gender.py
from enum import Enum

class DocumentsType(str, Enum):
    ACTE_DE_NAISSANCE = "ACTE_DE_NAISSANCE"
    ACTE_DE_MARIAGE = "ACTE_DE_MARIAGE"
    ACTE_DE_DECES = "ACTE_DE_DECES"
    CERTIFICAT_DE_NATIONALITE = "CERTIFICAT_DE_NATIONALITE"
    EXTRAIT_DU_CASIER_JUDICIAIRE = "EXTRAIT_DU_CASIER_JUDICIAIRE"
    EXTRAIT_DU_PLUMITIF = "EXTRAIT_DU_PLUMITIF"
