from enum import Enum as PyEnum

class RoleEnum(PyEnum):
    SUPER_ADMINISTRATEUR = "SUPER_ADMINISTRATEUR"
    ADMINISTRATEUR = "ADMINISTRATEUR"
    AGENT = "AGENT"
    OPERATEUR_SUR_SITE = "OPERATEUR_SUR_SITE"